//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormDemoDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.BookAuthors = new HashSet<BookAuthor>();
        }
    
        public string AuthorID { get; set; }
        public string FullName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<BookAuthor> BookAuthors { get; set; }
    }
}
