//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormDemoDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookAuthors = new HashSet<BookAuthor>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.RentalDetails = new HashSet<RentalDetail>();
            this.RentalPrices = new HashSet<RentalPrice>();
        }
    
        public string BookID { get; set; }
        public string CategoryID { get; set; }
        public string BookName { get; set; }
        public string PublisherID { get; set; }
        public string Edition { get; set; }
        public string Year { get; set; }
        public string LanguageID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual ICollection<BookAuthor> BookAuthors { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<RentalDetail> RentalDetails { get; set; }
        public virtual ICollection<RentalPrice> RentalPrices { get; set; }
    }
}
