//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormDemoDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalDetail
    {
        public string DetailID { get; set; }
        public string RentalID { get; set; }
        public string BookID { get; set; }
        public string Quanlity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Rental Rental { get; set; }
    }
}
