//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormDemoDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public Rental()
        {
            this.RentalDetails = new HashSet<RentalDetail>();
        }
    
        public string RentalID { get; set; }
        public string UserID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<System.DateTime> RentalDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<RentalDetail> RentalDetails { get; set; }
    }
}
