//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormDemoDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppier
    {
        public Suppier()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
