//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAuthor
    {
        public string BookAuthorID { get; set; }
        public string AuthorID { get; set; }
        public string BookID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
