//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalPrice
    {
        public string PriceID { get; set; }
        public string BookID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
